### ISSUE TITLE
Error in parsing the inp.xml

### ISSUE THREAD

**Issue by vamshimohank** [broeder-j/aiida-fleur#32]
Hi,

I am trying to run the Cu_bulk example and I get the following parsing error 

XMLSyntaxError: Element 'relPos', attribute 'label': The attribute 'label' is not allowed. (line 0)

I am using MaX-R2 version of fleur and the latest aiida-fleur. Am I missing something here?

**Comment by broeder-j** [comment]
Hi, Thanks for reporting. This has been fixed by recent commits 44627af09ed73559d57a754bb44f146cce599113 in develop. The XML Schema file and inp.xml of Fleur is changing lately, because new features get included. The to the plugin known xml Schemas were not updated to these until now (on the newest MaX release). (I myself ran a lot of calcs on an older MaX 1.3 dev thats why I just noticed)

**Comment by broeder-j** [comment]
I leave this open till:
1. I have checked if Fleur develop works (with further changes), and 
2. way to automatic test this 'fleur version' comparability is implemented

**Comment by broeder-j** [comment]
by the way: if you are interested in using/learning how to use aiida-fleur and writing workchains we have an upcoming workshop in February. If you or somebody else is interested contact us/me.

**Comment by vamshimohank** [comment]
Thank you for updating it and pushing in more examples. I am interested in running non-collinear magnetic calculations (spiral and DMI estimation) using Fleur and aiida, and so getting acquainted with it. 

Sure, I would be interested in writing workflows for it with your help.
